### ISSUE TITLE
undefined method `id' for class `Wisper::RSpec::EventRecorder' when using LoggerBroadcaster 

### ISSUE THREAD

**Issue by k-rudy** [krisleech/wisper#160]
Hey we use the following combination:

`wisper 2.0.0`
`wisper-rspec 0.0.2`

We use `LoggerBroadcaster` to make wiser logs consistent with the remaining application:

The listener is registered like that:

```ruby
WisperSubscriber.subscribe(ProfileListener)
```

our spec example is the following:

```ruby
it 'broadcasts profile_created_by_admin event', truncation: true do
  expect { subject }.to broadcast(:profile_created_by_admin)
end
```

```ruby
Wisper.configure do |config|
  config.broadcaster :default, Wisper::Broadcasters::LoggerBroadcaster.new(Rails.logger, Wisper::Broadcasters::SendBroadcaster.new)
  config.broadcaster :async,   Wisper::Broadcasters::LoggerBroadcaster.new(Sidekiq::Logging.logger, Wisper::SidekiqBroadcaster.new)
end
```

And it blows up when running the spec:

```
NameError:
       undefined method `id' for class `Wisper::RSpec::EventRecorder'
     # /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/wisper-2.0.0/lib/wisper/broadcasters/logger_broadcaster.rb:20:in `method'
     # /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/wisper-2.0.0/lib/wisper/broadcasters/logger_broadcaster.rb:20:in `block in name'
     # /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/wisper-2.0.0/lib/wisper/broadcasters/logger_broadcaster.rb:19:in `each'
     # /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/wisper-2.0.0/lib/wisper/broadcasters/logger_broadcaster.rb:19:in `find'
     # /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/wisper-2.0.0/lib/wisper/broadcasters/logger_broadcaster.rb:19:in `name'
     # /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/wisper-2.0.0/lib/wisper/broadcasters/logger_broadcaster.rb:12:in `broadcast'
     # /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/wisper-2.0.0/lib/wisper/registration/object.rb:18:in `broadcast'
     # /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/wisper-2.0.0/lib/wisper/publisher.rb:43:in `block in broadcast'
     # /Users/roody/.rvm/gems/ruby-2.3.1@profinda_saas/gems/wisper-2.0.0/lib/wisper/publisher.rb:42:in `broadcast'
     # ./app/models/concerns/events.rb:41:in `broadcast_event'
```

It blows up on this line https://github.com/krisleech/wisper/blob/master/lib/wisper/broadcasters/logger_broadcaster.rb#L20 when the object is an instance of `Wisper::RSpec::EventRecorder`

**Comment by k-rudy** [comment]
closing as it's more related to `wisper-rspec` gem and should be fixed there. Will reopen in `wisper-rspec`
