### ISSUE TITLE
undefined local variable or method `flash'

### ISSUE THREAD

**Issue by kirantpatil** [krisleech/wisper#165]
Hi,

Here I am getting location details from the api which is saved in db using LocationMessage model, as soon as it saves it hits global listener and there I am getting "undefined local variable or method flash" error

How to resolve this issue ?

I have global listener defined in incident controller as below.

```
def new
    flash[:notice] = "coollllll blah blah"
    @incident = Incident.new
     Wisper.subscribe(SmsListener.new)
end

  class SmsListener
    def emergency_location_creation_successful()
      flash[:notice] = "Location is saved"
    end
  end

```

Subscriber is defined in location_message model as below.

```
Class LocationMessage < ApplicationRecord
  include Wisper::Publisher

  after_save :publish_creation_successful

  def publish_creation_successful
    broadcast(:emergency_location_creation_successful)
  end
end
```

**Comment by kirantpatil** [comment]
### Error message
```

Started GET "/api/sms/incoming_sms?number=23456789" for 127.0.0.1 at 2017-11-06 13:09:00 +0530
Processing by API::V1::SmsController#incoming_sms as JSON
  Parameters: {"number"=>"23456789"}
   (0.1ms)  begin transaction
  SQL (0.3ms)  INSERT INTO "location_messages" ("number", "created_at", "updated_at") VALUES (?, ?, ?)  [["number", "23456789"], ["created_at", 2017-11-06 07:39:00 UTC], ["updated_at", 2017-11-06 07:39:00 UTC]]
   (0.1ms)  rollback transaction
Completed 500 Internal Server Error in 15ms (ActiveRecord: 1.1ms)


  
NameError (undefined local variable or method `flash' for #<IncidentsController::SmsListener:0x007f5c14c98228>):
  
app/controllers/incidents_controller.rb:80:in `emergency_location_creation_successful'
app/models/location_message.rb:8:in `publish_creation_successful'
app/controllers/api/v1/sms_controller.rb:21:in `incoming_sms'
  Rendering /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
  Rendered /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (6.3ms)
  Rendering /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
  Rendered /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.4ms)
  Rendering /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
  Rendered /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
  Rendered /home/fabritronix/.rvm/gems/ruby-2.4.1/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (23.7ms)

```

**Comment by strika** [comment]
You might want to use the block syntax in the controller and subscribe there:

```ruby
def new
  flash[:notice] = "coollllll blah blah"
  @incident = Incident.new

  @incident.on(:emergency_location_creation_successful) do
    flash[:notice] = "Location is saved"
  end

  # Do something with @incident here...
end
```

**Comment by andrewostroumov** [comment]
@kirantpatil you need to lead ruby...

**Comment by strika** [comment]
Sorry, I must have misread your code when I said `@incident.on ...`.

Where do you save `@sms` to the database and broadcast `:emergency_location_creation_successful` event? Maybe that happens in the `#create` action of the controller? Maybe you need to subscribe there?

This code doesn't really make sense since nothing happens with `@sms` after subscribing. Is this indeed your code?

**Comment by kirantpatil** [comment]
Yes, this is my code.

See, through api data is getting saved and I would like to get that data on my current screen which is Incident.
```

$ cat app/controllers/api/v1/sms_controller.rb 
class API::V1::SmsController < ApplicationController

  def incoming_sms
   contact = LocationMessage.new
   contact.number = params[:number]
   
   message = params[:message]
  
   if contact.save 
          render :json =>"Location Message saved", status: 201
   else
          render json: { errors: contact.errors}, status: 422
         end
   end
end
```

@sms is nothing but when I get api request that is stored in Location_message db as shown below.
```

[2] pry(main)> LocationMessage.last
  LocationMessage Load (0.4ms)  SELECT  "location_messages".* FROM "location_messages" ORDER BY "location_messages"."id" DESC LIMIT ?  [["LIMIT", 1]]
=> #<LocationMessage:0x000000060dcec8
 id: 29,
 number: "234567812345",
 created_at: Mon, 06 Nov 2017 15:02:56 IST +05:30,
 updated_at: Mon, 06 Nov 2017 15:02:56 IST +05:30,
 latitude: nil,
 longitude: nil,
 address: nil>

```

**Comment by strika** [comment]
I feel like you're misinterpreting what Wisper is for and what it can do.

Maybe you can ask yourself - "Can I solve this problem without Wisper - with plain Ruby and Rails?". If the answer is "Yes" then maybe you can use Wisper to organize code differently and make it nicer. If the answer is "No", then Wisper is not the solution for you. You need some different technology.

Wisper does not allow you to send events from one controller action to some other controller action or JavaScript frontend or something... directly.

**Comment by kirantpatil** [comment]
@strika, with global listener, we could listen events of other model/controller.

Please let me know, what do I need to do to solve this puzzle ?

Thanks.

**Comment by kirantpatil** [comment]
Hi and thanks everyone for helping hand and support.

I used gon gem with watch to resolve my issue.
